[package]
name = "rust_http_from_tcp"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
hex = "0.4.3"
reqwest = { version = "0.12.22", features = ["stream"] }
sha2 = "0.10.9"
sha256 = "1.6.0"
tokio = { version = "1.0", features = ["full"] }
tokio-util = "0.7.16"
